name: Build gui-v2 for pi

on:
  workflow_dispatch:
    inputs:
      gui_v2_ref:
        description: 'tag/branch to build'
        required: true
        type: string
        default: 'main'
      create_release:
        description: 'Create a GitHub release'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Required for creating releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: victronenergy/gui-v2
          ref: ${{ github.event.inputs.gui_v2_ref }}
          submodules: recursive

      - name: Version
        run: echo "version=$(git describe --tags --always)" >> $GITHUB_ENV  

      - name: Env
        run: ./scripts/build-gx-install-requirements.sh
      
      - name: Build
        run: ./scripts/build-gx.sh
    
      - name: Create tarball for deployment
        run: tar -czvf venus-gui-v2.tar.gz -C build-gx_files_to_copy .
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          path: venus-gui-v2.tar.gz
          retention-days: 90
      
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.steps.version.outputs.version }}',
              sha: context.sha
            })

      - name: Create or Update Release
        if: ${{ github.event.inputs.create_release }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.gui_v2_ref }}
          name: ${{ github.steps.version.outputs.version }}
          body_path: build-info.txt
          files: |
            venus-gui-v2.tar.gz
            install.sh
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
