name: Build gui-v2 for pi

on:
  workflow_dispatch:
    inputs:
      gui_v2_ref:
        description: 'tag/branch to build'
        required: true
        type: string
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: victronenergy/gui-v2
          ref: ${{ github.event.inputs.gui_v2_ref }}
          submodules: recursive
      
      - name: Run build-gx-install-requirements script
        run: ./scripts/build-gx-install-requirements.sh
      
      - name: Build for GX device
        run: ./scripts/build-gx.sh
      
      - name: Create tarball for deployment
        run: |
          cd build-gx_files_to_copy
          tar -czf ../venus-gui-v2.tar.gz .
          cd ..
          sha256sum venus-gui-v2.tar.gz > venus-gui-v2.tar.gz.sha256
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: venus-gui-v2
          path: |
            venus-gui-v2.tar.gz
            venus-gui-v2.tar.gz.sha256
          retention-days: 180
